config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get '/home/about' => 'homes#about'

  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  post '/users/:id' => 'books#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  attachment :profile_image

  validates :name,
    uniqueness: true,
    length: { minimum: 2, maximum: 20 }

  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if user_signed_in?
      user_path(current_user)
    else
      user_path(@user.id)
    end
  end

  protected # 呼び出された他のコントローラからも参照可能

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  # ユーザ登録(sign_up)の際に、ユーザ名(name)のデータ操作が許可される
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_to book_path(book)
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @user = User.find(current_user.id)
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path(book.id), notice: "You have updated book successfully."
    else
      @book = book
      render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
  		  <%= render  'users/error', model: @book %>

  		  <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, autofocus: true, class: "form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_field :body, class: "form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>

        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<p id="notice"></p>
  <div class="container px-5 px-sm-0">

　  <%= render  'users/error', model: @book %>
    <div class="row">
      <%= render 'users/userinfo', user: @user %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart", style="color: red;"><%= book.favorites.count %></i>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"><%= book.favorites.count %></i>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
<p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <%= render 'users/userinfo', user: @user %>

      <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fas fa-heart", style="color: red;"><%= @book.favorites.count %></i>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fas fa-heart"><%= @book.favorites.count %></i>
                  <% end %>
                <% end %>
              </td>
              <td><p>コメント数: <%= @book.book_comments.count %></p></td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
          </tr>
        </tbody>
      </table>

      <div class="comments">
        <% @book.book_comments.each do |book_comment| %>
          <table>
            <td>
              <%= attachment_image_tag book_comment.user,  :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
              <%= link_to book_comment.user.name, user_path(book_comment.user) %>
            </td>
            <td><%= book_comment.comment %></td>
            <td>
              <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
         </table>
        <% end %>

        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
      </div>

    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>

  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= notice %></p>

  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>

      </div>
    </div>
  </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <script src="https://kit.fontawesome.com/f3cb8c7832.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="fas fa-home nav-link text-light">
                  <%= link_to "Home", user_path(current_user.id) %>
                </li>
                <li class="fas fa-users nav-link text-light">
                  <%= link_to "Users", users_path %>
                </li>
                <li class="fas fa-book-open nav-link text-light">
                  <%= link_to "Books", books_path %>
                </li>
                <li class="fas fa-sign-out-alt nav-link text-light">
                  <%= link_to "logout", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li class="fas fa-home nav-link text-light">
                  <%= link_to "Home", root_path %>
                </li>
                <li class="fas fa-link nav-link text-light">
                  <%= link_to "About", home_about_path %>
                </li>
                <li class="fas fa-user-plus nav-link text-light">
                  <%= link_to "sign up", new_user_registration_path %>
                </li>
                <li class="fas fa-sign-in-alt nav-link text-light">
                  <%= link_to "login", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>



    <%= yield %>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_error.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>errors prohibited this obj from being saved:
  <ul>
  <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/_userinfo.html.erb
<head>
  <script src="https://kit.fontawesome.com/f3cb8c7832.js" crossorigin="anonymous"></script>
</head>

<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "attachment user profile_image fallback" %>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
	  </tr>
    <tr>
	    <th>introduction</th>
  	  <th><%= user.introduction %></th>
  	</tr>
  </table>

  <div class="row-md-3">
    <%= link_to edit_user_path(user) do %>
      <button class="btn btn-outline-secondary btn-block fas fa-user-cog" type="button"></button>
    <% end %>
  </div>

　<h2 class="mt-3">New book</h2>
　<%= form_with model: Book.new, local:true do |f| %>
　  <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_field :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= render  'users/error', model: @user %>
        
        <%= form_with model: @user, local:true do |f| %>

          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, placeholder:"名前", class: "form-control name" %>
          </div>
          <div class="form-group">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_field :introduction, autofocus: true, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render  'users/userinfo', user: @user, book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
<p id="notice">
  <%= notice %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render  'users/userinfo', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
        <% @books.each do |book| %>
          <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart", style="color: red;"><%= book.favorites.count %></i>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"><%= book.favorites.count %></i>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>
</main>